package runtime

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GenerateEnvFile creates the .env.treeman file in the worktree directory.
func GenerateEnvFile(state *RuntimeState) error {
	lines := buildEnvLines(state)
	content := strings.Join(lines, "\n") + "\n"

	envPath := filepath.Join(state.WorktreePath, filepath.Base(state.EnvFile))
	if err := os.WriteFile(envPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing env file: %w", err)
	}

	return nil
}

// buildEnvLines builds the environment variable lines for the .env.treeman file.
func buildEnvLines(state *RuntimeState) []string {
	var lines []string

	lines = append(lines, "# Generated by TreeMan — do not edit manually")
	lines = append(lines, fmt.Sprintf("TREEMAN_BRANCH=%s", state.Branch))
	lines = append(lines, fmt.Sprintf("TREEMAN_BRANCH_SLUG=%s", state.BranchSlug))
	lines = append(lines, fmt.Sprintf("TREEMAN_RUNTIME_NAME=%s-%s", state.Repo, state.BranchSlug))

	// Sort port names for deterministic output
	portNames := make([]string, 0, len(state.Ports))
	for name := range state.Ports {
		portNames = append(portNames, name)
	}
	sort.Strings(portNames)

	// Add port variables
	for _, name := range portNames {
		port := state.Ports[name]
		envName := strings.ToUpper(name) + "_PORT"
		lines = append(lines, fmt.Sprintf("%s=%d", envName, port))

		// Special case: "app" port is also exported as PORT
		if name == "app" {
			lines = append(lines, fmt.Sprintf("PORT=%d", port))
		}
	}

	// Add compose project name for docker-compose runtimes
	if state.ComposeProjectName != "" {
		lines = append(lines, fmt.Sprintf("COMPOSE_PROJECT_NAME=%s", state.ComposeProjectName))
	}

	return lines
}

// ComposeProjectName generates a unique Docker Compose project name from repo + branch.
// Replaces non-alphanumeric characters with underscores.
func ComposeProjectName(repo, branchSlug string) string {
	name := repo + "_" + branchSlug
	var result strings.Builder
	for _, c := range name {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' {
			result.WriteRune(c)
		} else {
			result.WriteRune('_')
		}
	}
	return strings.ToLower(result.String())
}
