package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

const posixShellIntegration = `# TreeMan shell integration
# Generated by: treeman shell init %[1]s
treeman() {
  local _tm_output _tm_status
  case "$1" in
    create|branch|review|switch|clean|delete|wtb|wtpr|wtmr|wts|wtc|wtd)
      _tm_output=$(command treeman "$@")
      _tm_status=$?
      if [ "$_tm_status" -ne 0 ]; then
        return "$_tm_status"
      fi
      if [ -d "$_tm_output" ]; then
        cd "$_tm_output"
      elif [ -n "$_tm_output" ]; then
        printf '%%s\n' "$_tm_output"
      fi
      ;;
    *)
      command treeman "$@"
      ;;
  esac
}

wt() { treeman create "$@"; }
wtb() { treeman branch "$@"; }
wtpr() { treeman review "$@"; }
wtmr() { treeman review "$@"; }
wts() { treeman switch "$@"; }
wtl() { treeman list "$@"; }
wtc() { treeman clean "$@"; }
wtd() { treeman delete "$@"; }
`

const fishShellIntegration = `# TreeMan shell integration
# Generated by: treeman shell init fish
function treeman
  switch $argv[1]
    case create branch review switch clean delete wtb wtpr wtmr wts wtc wtd
      set -l _tm_output (command treeman $argv)
      set -l _tm_status $status
      if test $_tm_status -ne 0
        return $_tm_status
      end
      if test -d "$_tm_output"
        cd "$_tm_output"
      else if test -n "$_tm_output"
        printf '%s\n' "$_tm_output"
      end
    case '*'
      command treeman $argv
  end
end

function wt; treeman create $argv; end
function wtb; treeman branch $argv; end
function wtpr; treeman review $argv; end
function wtmr; treeman review $argv; end
function wts; treeman switch $argv; end
function wtl; treeman list $argv; end
function wtc; treeman clean $argv; end
function wtd; treeman delete $argv; end
`

func writeShellInit(out interface{ Write([]byte) (int, error) }, shell string) error {
	switch shell {
	case "bash", "zsh":
		_, err := fmt.Fprintf(out, posixShellIntegration, shell)
		return err
	case "fish":
		_, err := out.Write([]byte(fishShellIntegration))
		return err
	default:
		return fmt.Errorf("unsupported shell %q: use 'bash', 'zsh', or 'fish'", shell)
	}
}

// newInitCmd preserves the original shell initialization command for existing
// startup files. New configuration should use "treeman shell install".
func newInitCmd() *cobra.Command {
	return &cobra.Command{
		Use:       "init <shell>",
		Short:     "Print shell integration functions",
		Hidden:    true,
		Args:      cobra.ExactArgs(1),
		ValidArgs: []string{"bash", "zsh", "fish"},
		RunE: func(cmd *cobra.Command, args []string) error {
			return writeShellInit(cmd.OutOrStdout(), args[0])
		},
	}
}
