package cmd

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

// shortcut is one interactive shell shortcut. Every prefix in shortcutPrefixes
// is joined with suffix to name a shell function that runs command.
type shortcut struct {
	suffix  string
	command string
	// followsDir reports whether command can report a destination directory.
	// Only those names need the adapter to hand over TREEMAN_CD_FILE.
	followsDir bool
}

// shortcutPrefixes are the shorthand families the integration defines. "tm" is
// the current shorthand. "wt" predates it and stays so that shells configured
// by earlier TreeMan versions keep working.
//
// Every family is defined directly against treeman rather than one delegating
// to another. A delegating definition would resolve its target when the user
// calls it, so binding that name to anything else would silently redirect the
// other family.
var shortcutPrefixes = []string{"tm", "wt"}

// shortcuts is the single source for the shell functions, for the adapter's
// command list, and for every command's cobra aliases. Add a shortcut here,
// not in the templates below.
var shortcuts = []shortcut{
	{suffix: "", command: "create", followsDir: true},
	{suffix: "b", command: "branch", followsDir: true},
	{suffix: "pr", command: "review", followsDir: true},
	{suffix: "mr", command: "review", followsDir: true},
	{suffix: "s", command: "switch", followsDir: true},
	{suffix: "l", command: "list"},
	{suffix: "c", command: "clean", followsDir: true},
	{suffix: "d", command: "delete", followsDir: true},
}

// commandAliases returns the shortcut names cobra accepts for command, so that
// "treeman tmb" reaches "branch". A bare prefix is never an alias: "tm" runs
// create through a shell function and has never been a subcommand.
func commandAliases(command string) []string {
	var aliases []string
	for _, prefix := range shortcutPrefixes {
		for _, s := range shortcuts {
			if s.command == command && s.suffix != "" {
				aliases = append(aliases, prefix+s.suffix)
			}
		}
	}
	return aliases
}

// adapterNames returns every first argument the treeman adapter must treat as
// a command that can report a destination: the canonical command names, then
// the shortcut aliases for them.
func adapterNames() []string {
	var names []string
	seen := make(map[string]bool, len(shortcuts))
	for _, s := range shortcuts {
		if s.followsDir && !seen[s.command] {
			seen[s.command] = true
			names = append(names, s.command)
		}
	}
	for _, prefix := range shortcutPrefixes {
		for _, s := range shortcuts {
			if s.followsDir && s.suffix != "" {
				names = append(names, prefix+s.suffix)
			}
		}
	}
	return names
}

// shortcutDefinitions renders one function definition per shortcut. The format
// takes the function name and the command that the function runs.
func shortcutDefinitions(format string) string {
	var out strings.Builder
	for _, prefix := range shortcutPrefixes {
		for _, s := range shortcuts {
			fmt.Fprintf(&out, format, prefix+s.suffix, s.command)
		}
	}
	return out.String()
}

const posixShellIntegration = `# TreeMan shell integration
# Generated by: treeman shell init %[1]s
treeman() {
  case "$1" in
    %[2]s)
      local _tm_file _tm_status
      # TreeMan writes the directory to change to into this file. Nothing is
      # captured, so a command started by --exec inherits the terminal.
      _tm_file=$(mktemp 2>/dev/null) || {
        # TreeMan still runs; say why it stopped changing directory rather
        # than leaving the caller to wonder.
        echo "treeman: mktemp is unavailable, so this shell cannot follow the worktree" >&2
        command treeman "$@"
        return $?
      }
      TREEMAN_CD_FILE="$_tm_file" command treeman "$@"
      _tm_status=$?
      if [ "$_tm_status" -eq 0 ] && [ -s "$_tm_file" ]; then
        cd -- "$(cat "$_tm_file")" || _tm_status=$?
      fi
      rm -f "$_tm_file"
      return "$_tm_status"
      ;;
    *)
      command treeman "$@"
      ;;
  esac
}

%[3]s`

const fishShellIntegration = `# TreeMan shell integration
# Generated by: treeman shell init fish
function treeman
  switch $argv[1]
    case %[1]s
      # TreeMan writes the directory to change to into this file. Nothing is
      # captured, so a command started by --exec inherits the terminal.
      # Ask before calling, because fish reports a missing command itself and
      # that report is not the command's stderr to redirect.
      set -l _tm_file
      if type -q mktemp
        set _tm_file (mktemp 2>/dev/null)
      end
      if test -z "$_tm_file"
        # TreeMan still runs; say why it stopped changing directory rather
        # than leaving the caller to wonder.
        echo "treeman: mktemp is unavailable, so this shell cannot follow the worktree" >&2
        command treeman $argv
        return $status
      end
      set -lx TREEMAN_CD_FILE "$_tm_file"
      command treeman $argv
      set -l _tm_status $status
      if test $_tm_status -eq 0; and test -s "$_tm_file"
        cd (cat "$_tm_file"); or set _tm_status $status
      end
      rm -f "$_tm_file"
      return $_tm_status
    case '*'
      command treeman $argv
  end
end

%[2]s`

func writeShellInit(out interface{ Write([]byte) (int, error) }, shell string) error {
	switch shell {
	case "bash", "zsh":
		_, err := fmt.Fprintf(out, posixShellIntegration,
			shell,
			strings.Join(adapterNames(), "|"),
			shortcutDefinitions("%s() { treeman %s \"$@\"; }\n"))
		return err
	case "fish":
		_, err := fmt.Fprintf(out, fishShellIntegration,
			strings.Join(adapterNames(), " "),
			shortcutDefinitions("function %s; treeman %s $argv; end\n"))
		return err
	default:
		return fmt.Errorf("unsupported shell %q: use 'bash', 'zsh', or 'fish'", shell)
	}
}

// newInitCmd preserves the original shell initialization command for existing
// startup files. New configuration should use "treeman shell install".
func newInitCmd() *cobra.Command {
	return &cobra.Command{
		Use:       "init <shell>",
		Short:     "Print shell integration functions",
		Hidden:    true,
		Args:      cobra.ExactArgs(1),
		ValidArgs: []string{"bash", "zsh", "fish"},
		RunE: func(cmd *cobra.Command, args []string) error {
			return writeShellInit(cmd.OutOrStdout(), args[0])
		},
	}
}
