package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

// shellWrappers contains the shell functions that must be sourced into the
// user's shell session so that treeman can cd into new worktrees.
//
// The pattern mirrors how direnv / zoxide work:
//   - Each shell function calls the treeman binary for all logic.
//   - The binary prints the target directory path to stdout.
//   - The wrapper captures that output and runs cd.
//   - All user-facing messages go to stderr from the binary.
const shellWrappers = `# TreeMan shell integration
# Generated by: treeman init %[1]s
# Add this to your ~/.%[1]src or ~/.profile:
#   eval "$(treeman init %[1]s)"

wt() {
  local _tm_dir
  _tm_dir=$(treeman create "$@") || return $?
  [ -n "$_tm_dir" ] && cd "$_tm_dir"
}

wtb() {
  local _tm_dir
  _tm_dir=$(treeman branch "$@") || return $?
  [ -n "$_tm_dir" ] && cd "$_tm_dir"
}

wtpr() {
  local _tm_dir
  _tm_dir=$(treeman review "$@") || return $?
  [ -n "$_tm_dir" ] && cd "$_tm_dir"
}

wtmr() {
  local _tm_dir
  _tm_dir=$(treeman review "$@") || return $?
  [ -n "$_tm_dir" ] && cd "$_tm_dir"
}

wts() {
  local _tm_dir
  _tm_dir=$(treeman switch "$@") || return $?
  [ -n "$_tm_dir" ] && cd "$_tm_dir"
}

wtd() {
  treeman delete "$@"
}

wto() {
  treeman open "$@"
}

lg() {
  if ! command -v lazygit >/dev/null 2>&1; then
    echo "Warning: lazygit is not installed." >&2
    return 1
  fi

  local _tm_newdir_file="$HOME/.lazygit/newdir"
  mkdir -p "$HOME/.lazygit"

  LAZYGIT_NEW_DIR_FILE="$_tm_newdir_file" lazygit "$@"

  if [ -f "$_tm_newdir_file" ]; then
    local _tm_target
    _tm_target=$(cat "$_tm_newdir_file")
    rm -f "$_tm_newdir_file"
    if [ -n "$_tm_target" ] && [ "$_tm_target" != "$(pwd)" ]; then
      cd "$_tm_target"
    fi
  fi
}
`

func newInitCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init <shell>",
		Short: "Print shell integration functions",
		Long: `Print the shell wrapper functions for the specified shell.

Add this to your shell configuration file:

  # bash (~/.bashrc):
  eval "$(treeman init bash)"

  # zsh (~/.zshrc):
  eval "$(treeman init zsh)"

This defines the wt, wtb, wtpr, wtmr, wts, wtd, wto, and lg functions in your shell
session, enabling automatic cd into new or switched worktrees.`,
		Args:      cobra.ExactArgs(1),
		ValidArgs: []string{"bash", "zsh"},
		RunE: func(cmd *cobra.Command, args []string) error {
			shell := args[0]
			switch shell {
			case "bash", "zsh":
				fmt.Fprintf(cmd.OutOrStdout(), shellWrappers, shell)
				return nil
			default:
				return fmt.Errorf("unsupported shell %q: use 'bash' or 'zsh'", shell)
			}
		},
	}
}
